### ISSUE TITLE
ProcessReads: Command terminated by signal 11

### ISSUE THREAD

**Issue by ksahlin** [ydLiu-HIT/deSALT#10]
Hi again, 

I'm trying to run deSALT on an 890k reads ONT dataset found [here](https://s3.amazonaws.com/nanopore-human-wgs/rna/fastq/Bham_Run1_20171115_1D.pass.dedup.fastq) (from this webpage: https://github.com/nanopore-wgs-consortium/NA12878/blob/master/nanopore-human-transcriptome/fastq_fast5_bulk.md). and I run into the error below. The job seems to take around 45Gb with 2 cores and there is 512GB available so I don't think that is an issue.

```
[Main] deSALT - De Bruijn graph-based Spliced Aligner for Long Transcriptome reads
[Param-INFO] deSALT parameters:index-kmer:22    seed-lmer:15    hash-kmer:8     thread:2        strand_diff:20  identify junction:both_strand
[Phase-INFO] Loading Index and Reads
[Phase-INFO] Seeding and Chaining Phase (first-pass)
[Skeleton-generation] Generating skeletons of 655350 reads, total 533940096 bases in 1402.459184 seconds
[Skeleton-generation] Generating skeletons of 235153 reads, total 188651918 bases in 453.295283 seconds
[Phase-INFO] Total 890503 reads were processed in 1859.613 seconds (first-pass)
[Phase-INFO] Refined Alignment Phase (second-pass)
[Phase-INFO] Exons inference by skeletons of all reads
[Phase-INFO] Loading GTF annotations
[Phase-INFO] Inferring total 119352 isolated regions (pseudo-exons) after merging and filtering
[Phase-INFO] Refining pseudo-exons by scoring matrix
[Loop-ProcessReads] The 0st loop of refined alignment procedure with 178102 reads......
Command terminated by signal 11
```

```
 Command being timed: "deSALT aln path/to/index  ont_human.fq -t 2 --gtf annotation.info -o reads.sam"
```

Any ideas? 

Best,
Kristoffer

**Comment by ydLiu-HIT** [comment]
Hi Kristoffer:

I just re-run the ONT dataset you have supported with deSALT(v1.5), but I didn't find any crash.
```
[Main] deSALT - De Bruijn graph-based Spliced Aligner for Long Transcriptome reads
[Param-INFO] deSALT parameters:index-kmer:22	seed-lmer:15	hash-kmer:8	thread:18	strand_diff:20	identify junction:both_strand
[Phase-INFO] Loading Index and Reads
[Phase-INFO] Seeding and Chaining Phase (first-pass)
[Skeleton-generation] Generating skeletons of 655350 reads, total 533940096 bases in 250.945120 seconds
[Skeleton-generation] Generating skeletons of 235153 reads, total 188651918 bases in 81.145082 seconds
[Phase-INFO] Total 890503 reads were processed in 332.117 seconds (first-pass)
[Phase-INFO] Refined Alignment Phase (second-pass)
[Phase-INFO] Exons inference by skeletons of all reads
[Phase-INFO] Loading GTF annotations
[Phase-INFO] Inferring total 114048 isolated regions (pseudo-exons) after merging and filtering
[Phase-INFO] Refining pseudo-exons by scoring matrix
[Loop-ProcessReads] The 0st loop of refined alignment procedure with 178102 reads......
[Loop-ProcessReads] Aligned 176483 reads to genome, and confirmed total 72898 exons' strand in 61.752164 seconds
[Loop-ProcessReads] The 1st loop of refined alignment procedure with 178102 reads......
[Loop-ProcessReads] Aligned 175567 reads to genome, and confirmed total 75460 exons' strand in 48.197428 seconds
[Loop-ProcessReads] The 2st loop of refined alignment procedure with 178102 reads......
[Loop-ProcessReads] Aligned 176215 reads to genome, and confirmed total 77273 exons' strand in 47.554849 seconds
[Loop-ProcessReads] The 3st loop of refined alignment procedure with 178102 reads......
[Loop-ProcessReads] Aligned 176444 reads to genome, and confirmed total 78715 exons' strand in 47.547694 seconds
[Loop-ProcessReads] The 4st loop of refined alignment procedure with 178095 reads......
[Loop-ProcessReads] Aligned 176455 reads to genome, and confirmed total 79933 exons' strand in 45.603060 seconds
[Phase-INFO] Total 881164 reads were mapped to genome in 263.669234 seconds (second-pass)
[Phase-INFO] Finishing Alignment
[Phase-INFO] Command: @PG	ID:deSALT	PN:deSALT	VN:1.5	CL:deSALT aln -t 18 -Q -G human.info -o human_gtf.sam deSALT_Revision/INDEX/deBGAIndex/human/ Bham_Run1_20171115_1D.pass.dedup.fastq
[Main] Real time: 844.258 sec; CPU: 10211.560 sec, Memory peak: 35.75 GB
```
So I think you may have other errors when running deSALT in following aspects:
1. The version of deBGA you have used when creating RdBG index. Compare to the original deBGA program, I have made some changes, so the executable program of deBGA in my folder is recommended.
2. Do you have run two deSALT programs at the same time, if so, you should run deSALT with different specified tempory file prefix(-f).
3. You run deSALT with GTF mode. I suggest you try to run deSALT without GTF information, if no issues appear, the annotation file(GTF format) you have used may have some errors.

Best, looking forward to your reply.
Yadong

**Comment by ksahlin** [comment]
Hi Yadong,

Thanks for the very thorough answer! I tried suggestion no. 2 but still got the same error ( I did have 2 jobs running in parallel). I'm going to try your suggestion no. 1 next, by using the deBGA file present in the src folder and run
```
src/./deBGA index {input.ref} {output.desalt_index_folder}
```
 Also, I'm running deSALT in a snakemake pipeline, and snakemake puts a file `.snakemake_timestamp` in the index folder when the indexing is completed, will this be an issue when loading/using the index?

Thanks for your help,
Kristoffer

**Comment by ydLiu-HIT** [comment]
Hi Kristoffer,

I think there will be no issue when loading/using the index. In fact, desalt loads the indexs by identifying some fixed file names in the folder(eg. unipath_g.hash), additional files have no effect to the indexs.

Best.
Yadong

**Comment by ydLiu-HIT** [comment]
Also, I have pre-build the RdBG index of human with release 97 of GRCh38 genomes, you can download and use the indexs directly: https://drive.google.com/open?id=11E2j1X5jGqKNVtyNHsfPjqnu-fVBgyoi

**Comment by ksahlin** [comment]
Hi again,

So I tried suggestion number 1 and got the same error. However, when I removed the GTF mode (suggestion 3) -- it ran fine without errors! Therefore we need to key in on the GTF annotations file. 

The only modification I did was the if statement taking care of the "#" lines in the beginning of the file.

My ideas: Could it be something such as the chromosomes being labeled as 1,2,..,X,Y, MT in the genome fasta, but labelled chr1, chr2,..., chrX,chrY,chrM in the gtf (or vice versa)?  I think there is still not a consensus on how to label them. Also, what about any additional "alternative" reference segments present in either the reference fasta or reference GTF annotations? What happens in this case.

Best,
Kristoffer

**Comment by ydLiu-HIT** [comment]
Hi Kristoffer,

1. The label of chromosomes should be the same between the genome and gtf. If not the same, the annotations will be no use but couldn't cause the crash I think. 
2. Maybe I know the key point of the crash, in the original GTF file, exons from the transcript in ‘-’ strand are sorted in reverse order. But when I use gffread, the problem will be overcome.  So I ignore the problem in Annotation_Load.py.  Now I have addressed this problem in Annotation_Load.py, and update to GitHub release v1.5.1, you can download the latest version and try Annotation_Load.py again to get genome annotation information.

Thanks for your report, this helps me to address some point which I have ignored. And I hope this will solve your problems.

Best,
Yadong

**Comment by ydLiu-HIT** [comment]
Usually, I will remove additional "alternative" reference segments present in either the reference genome or reference GTF annotations, just retain primary assembly information (chr1, chr2,..., chrX,chrY,chrM).

**Comment by ksahlin** [comment]
Great, thanks for the feedback! I fixed the headers in my fasta genome and installed the new version and running new version of `annotation_Load.py`. Should be good to go soon! 

I'm having a minor hiccup though: I'm have the following error when rerunning the indexing using `./deBGA index` which is hopefully easy to debug. Any ideas why this code exits with non-zero exit status? (I didn't find what non-zero exit status 17 means)

```
kmer size to build index: 22
256 files to be written in folder div
Has finished loading chr1
Has finished loading chr10
Has finished loading chr11
Has finished loading chr12
Has finished loading chr13
Has finished loading chr14
Has finished loading chr15
Has finished loading chr16
Has finished loading chr17
Has finished loading chr18
Has finished loading chr19
Has finished loading chr2
Has finished loading chr20
Has finished loading chr21
Has finished loading chr22
Has finished loading chr3
Has finished loading chr4
Has finished loading chr5
Has finished loading chr6
Has finished loading chr7
Has finished loading chr8
Has finished loading chr9
Has finished loading chrM
Has finished loading chrX
Has finished loading chrY
Has finished loading KI270728.1
Has finished loading KI270727.1
...
Has finished loading KI270394.1
total number of lines: 1440565596
total number of positions on ref seq: 1515846309
total number of chars to allocate for ref seq: 378961584
hash_n: 268435456
total number of chars to allocate: 5762262384
has finished 0 file sorting: 21997003
has finished 0 file loading
...
has finished 253 file loading
has finished 254 file sorting: 10963391
has finished 254 file loading
has finished 255 file sorting: 22218687
has finished 255 file loading
finish filling the hash blank
begin creating unipath: 268435456
number of supernode: 28915315
number of linear node: 1185942590
number of forward Y branch node: 5708341
number of reverse Y branch node: 5705576
number of X branch node: 5194665
number of linear blunt node: 375
number of branch blunt node: 0
number of end blunt node: 0
number of ends blunt node: 0
the max length of supernode: 8532
begin wrtting hash and kmer array and offset on unipath into file 1202551547
begin writing info about size of index files
rm: cannot remove '/nfs/brubeck.bx.psu.edu/scratch4/ksahlin/ultra_eval/alignments/desalt/simulated/index/div/': Directory not empty
Program finished
deleting div temporary index file folder
rm -rf /nfs/brubeck.bx.psu.edu/scratch4/ksahlin/ultra_eval/alignments/desalt/simulated/index/div/ ---
rm /nfs/brubeck.bx.psu.edu/scratch4/ksahlin/ultra_eval/alignments/desalt/simulated/index/unipath.seq ***
finish index building
Command exited with non-zero status 17
 Command being timed: "./deBGA index Homo_sapiens.GRCh38.dna.primary_assembly_modified_headers.fa  /index
```

**Comment by ksahlin** [comment]
and this is what the index folder looks like after the error is thrown.

```
[ksahlin@desmond evaluation]$ ls -l ont_human/index/
total 15335553
drwxrwxr-x 2 ksahlin ksahlin          2 Nov 28 05:26 div
-rw-rw-r-- 1 ksahlin ksahlin       6112 Nov 28 04:23 N.sta
-rw-rw-r-- 1 ksahlin ksahlin  378961584 Nov 28 04:23 ref.seq
-rw-rw-r-- 1 ksahlin ksahlin       4115 Nov 28 04:23 unipath.chr
-rw-rw-r-- 1 ksahlin ksahlin 2147483656 Nov 28 05:09 unipath_g.hash
-rw-rw-r-- 1 ksahlin ksahlin 4810206188 Nov 28 05:10 unipath_g.kmer
-rw-rw-r-- 1 ksahlin ksahlin 9620412376 Nov 28 05:11 unipath_g.offset
-rw-rw-r-- 1 ksahlin ksahlin 1834052840 Nov 28 05:25 unipath.pos
-rw-rw-r-- 1 ksahlin ksahlin  231322528 Nov 28 05:25 unipath.posp
-rw-rw-r-- 1 ksahlin ksahlin  452444160 Nov 28 05:25 unipath.seqb
-rw-rw-r-- 1 ksahlin ksahlin  231322528 Nov 28 05:09 unipath.seqfb
-rw-rw-r-- 1 ksahlin ksahlin         80 Nov 28 05:25 unipath.size
```

**Comment by ydLiu-HIT** [comment]
Hi Kristoffer,

1. I think the RdBG index has been created successfully from the result and the output of "Program finished". You can run `deSALT aln` directly with the index and test the result.
2. The non-zero error maybe comes from the deletion of "div temporary index file folder". I will test and find the problem and feedback to you.

Thanks, Best,
Yadong

**Comment by ydLiu-HIT** [comment]
Hi Kristoffer,
 
I can't find any crash with my reference genome(release 92 of GRCh38 in Ensembl, only include primary assembly information). What's more, the total file sizes of the results in your index folder seem to be much smaller than my(35GB in total). So can you share with me the reference genome you have used in order to the further detection of the error?

Thanks,
Yadong

**Comment by ksahlin** [comment]
How does the indexing step treat newlines in the reference fasta? 

In the original reference fasta file I use (ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz) the sequence is cut in lines of 80bp before a newline. When I change the headers of the fasta so that `1 -> chr1,...,X->chrX, MT->chrM` to conform with the headers in the GTF file. In my script that does header conversion of the fasta, the sequence is written to the new fasta file without newlines. Could this be the cause of the smaller index file size? and maybe also the abnormal exit?

I can of course change my modification script to preserve newlines in the sequence, but maybe this is worth to hash out, whether this is problematic to deSALT?

**Comment by ydLiu-HIT** [comment]
Yes, I think I found the point of the error.

Because deSALT creates RdBG index depends on deBGA, but before I found deBGA will have errors when the bases write in one line without a fixed cut. But I am not the author of deBGA, I just make some minor changes to adapt my program, so I suggest you just change the headers but still keep lines with a 80bp cut.

Hope everything is fine after you do that.
Best, Yadong

**Comment by ksahlin** [comment]
So I reran with 80bp cut, now the total index size of `release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa` is about 35Gb (see below index directory). 

```
[ksahlin@desmond evaluation]$ ls -l ont_human/index/
total 30159444
drwxrwxr-x 2 ksahlin ksahlin           2 Nov 29 09:03 div
-rw-rw-r-- 1 ksahlin ksahlin        8016 Nov 29 06:17 N.sta
-rw-rw-r-- 1 ksahlin ksahlin   774937680 Nov 29 06:16 ref.seq
-rw-rw-r-- 1 ksahlin ksahlin        4124 Nov 29 06:16 unipath.chr
-rw-rw-r-- 1 ksahlin ksahlin  2147483656 Nov 29 08:10 unipath_g.hash
-rw-rw-r-- 1 ksahlin ksahlin  9450488936 Nov 29 08:13 unipath_g.kmer
-rw-rw-r-- 1 ksahlin ksahlin 18900977872 Nov 29 08:13 unipath_g.offset
-rw-rw-r-- 1 ksahlin ksahlin  4363696920 Nov 29 09:01 unipath.pos
-rw-rw-r-- 1 ksahlin ksahlin   512355424 Nov 29 09:01 unipath.posp
-rw-rw-r-- 1 ksahlin ksahlin   926892032 Nov 29 09:01 unipath.seqb
-rw-rw-r-- 1 ksahlin ksahlin   512355424 Nov 29 08:08 unipath.seqfb
-rw-rw-r-- 1 ksahlin ksahlin          80 Nov 29 09:01 unipath.size
```

As you note, I agree that it is the removal of the div folder that probably causes the error:

```
...
the max length of supernode: 7683
begin wrtting hash and kmer array and offset on unipath into file 2362622234
begin writing info about size of index files
rm: cannot remove 'ont_human/index/div/': Directory not empty
Program finished
deleting div temporary index file folder
rm -rf /ont_human/index/div/ ---
rm ont_human/index/unipath.seq ***
finish index building

[desalt_index] Indexing undoing, deBGA index exit abnormally.
```

I'm fine with closing this issue. Maybe the `rm` issue could be fixed though because this error is a bit inconvenient for pipelines. For example, doing `rm -rf` directly on the `index/div` could probably work.

**Comment by ksahlin** [comment]
Actually it seems that the alignment error is back

This is first lines of my annotation.info file (I used your new commit to parse the annotation)
```
(py36) [ksahlin@desmond]$ head ont_human/annotation.info
1478937	1231851
chr1	ENST00000456328.2|ENSG00000223972.5	+	3	11869,12227,12613,12721,13221,14409,
chr1	ENST00000450305.2|ENSG00000223972.5	+	6	12010,12057,12179,12227,12613,12697,12975,13052,13221,13374,13453,13670,
chr1	ENST00000488147.1|ENSG00000227232.5	-	11	29534,29570,24738,24891,18268,18366,17915,18061,17606,17742,17233,17368,16858,17055,16607,16765,15796,15947,15005,15038,14404,14501,
chr1	ENST00000619216.1|ENSG00000278267.1	-	1	17369,17436,
chr1	ENST00000473358.1|ENSG00000243485.5	+	3	29554,30039,30564,30667,30976,31097,
chr1	ENST00000469289.1|ENSG00000243485.5	+	2	30267,30667,30976,31109,
chr1	ENST00000607096.1|ENSG00000284332.1	+	1	30366,30503,
chr1	ENST00000417324.1|ENSG00000237613.2	-	3	35721,36081,35277,35481,34554,35174,
chr1	ENST00000461467.1|ENSG00000237613.2	-	2	35721,36073,35245,35481,
```
Here is the error:

```
...
[Main] deSALT - De Bruijn graph-based Spliced Aligner for Long Transcriptome reads
[Param-INFO] deSALT parameters:index-kmer:22    seed-lmer:14    hash-kmer:8     thread:48       strand_diff:10  identify junction:both_strand
[Phase-INFO] Loading Index and Reads
[Phase-INFO] Seeding and Chaining Phase (first-pass)
[Skeleton-generation] Generating skeletons of 655350 reads, total 533940096 bases in 392.548555 seconds
[Skeleton-generation] Generating skeletons of 235153 reads, total 188651918 bases in 128.433888 seconds
[Phase-INFO] Total 890503 reads were processed in 521.029 seconds (first-pass)
[Phase-INFO] Refined Alignment Phase (second-pass)
[Phase-INFO] Exons inference by skeletons of all reads
[Phase-INFO] Loading GTF annotations
[Phase-INFO] Inferring total 116690 isolated regions (pseudo-exons) after merging and filtering
[Phase-INFO] Refining pseudo-exons by scoring matrix
[Loop-ProcessReads] The 0st loop of refined alignment procedure with 178102 reads......
Command terminated by signal 11
        Command being timed: "deSALT aln ont_human/index  ont_human.fq -d 10 -s 2 -l 14 -t 48 --gtf  ont_human/annotation.info -o  ont_human/reads.sam -f /tmp/tmp4bcs9_z2/desalt_temp_prefix"
```
I will try running deSALT without the gtf annotation again tomorrow

**Comment by ydLiu-HIT** [comment]
Hi Kristoffer,

I think or are you sure you are using the new version `Annotation_Load.py` in release v1.5.1. If you use the new version, you should get the following genome information:

```
1362975 1136254
chr1    ENST00000456328|ENSG00000223972 +       3       11869,12227,12613,12721,13221,14409,
chr1    ENST00000450305|ENSG00000223972 +       6       12010,12057,12179,12227,12613,12697,12975,13052,13221,13374,13453,13670,
chr1    ENST00000488147|ENSG00000227232 -       11      14404,14501,15005,15038,15796,15947,16607,16765,16858,17055,17233,17368,17606,17742,17915,18061,18268,18366,24738,24891,29534,29570,
chr1    ENST00000619216|ENSG00000278267 -       1       17369,17436,
chr1    ENST00000473358|ENSG00000243485 +       3       29554,30039,30564,30667,30976,31097,
chr1    ENST00000469289|ENSG00000243485 +       2       30267,30667,30976,31109,
chr1    ENST00000607096|ENSG00000284332 +       1       30366,30503,
chr1    ENST00000417324|ENSG00000237613 -       3       34554,35174,35277,35481,35721,36081,
chr1    ENST00000461467|ENSG00000237613 -       2       35245,35481,35721,36073,
```

All the exons should be in ascending order according to their position in the genome, but you get reverse order in the transcript for '-' strand, such as :
`chr1	ENST00000417324.1|ENSG00000237613.2	-	3	35721,36081,35277,35481,34554,35174,`

**Comment by ksahlin** [comment]
I checked and I had the new version of the script but apparently the annotations file had not been updated, so I reran the script and everything works now. 

Thanks so much for all your prompt help,
Kristoffer
