### ISSUE TITLE
Input error: -k cannot be less than 14 or more than 14

### ISSUE THREAD

**Issue by ksahlin** [ydLiu-HIT/deSALT#11]
Hi,

I'm running 

```
deSALT aln path/to/index  ont_human.fq  -d 10 -s 2 -k 14 -t 32  -o reads.sam  -f /tmp/tmptjksjwp5/desalt_temp_prefix
```
And get the following output
```
[Main] deSALT - De Bruijn graph-based Spliced Aligner for Long Transcriptome reads
Input error: -k cannot be less than 14 or more than 14
```

**Comment by ydLiu-HIT** [comment]
Hi, 

you should run with the following command:

deSALT aln path/to/index  ont_human.fq  -d 10 -s 2 -l 14 -t 32  -o reads.sam  -f /tmp/tmptjksjwp5/desalt_temp_prefix

replace `-k` with `-l`
`-k` is the RdBG index kmer length, `-l` is the seeding kmer length which is less than index kmer.

**Comment by ksahlin** [comment]
Ok great, that's what I was looking for!
