### ISSUE TITLE
Indexing undoing, deBGA index exit abnormally

### ISSUE THREAD

**Issue by defendant602** [ydLiu-HIT/deSALT#12]
Hi,
   I have been testing deSALT and I installed deSALT using conda. When I run desalt index on human genome like this: "deSALT index /MY_PATH/hg38.fa /MY_PATH/hg38.fa.desalt.idx", in the stderr it said:
[desalt_index] Ececuting deBGA index ...

[desalt_index] Indexing undoing, deBGA index exit abnormally.

These are the last lines in the stdout:
has finished 254 file sorting: 22362873
has finished 254 file loading
has finished 255 file sorting: 45461535
has finished 255 file loading
finish filling the hash blank
begin creating unipath: 268435456

I don't see any error information in the stdout and I don't know why the program exited abnormally. Could you help me to check this out?

Thanks!

**Comment by defendant602** [comment]
I checked my SGE status and it looked most likely it's because the memory issue, since it requires 73G RAM for human genome.

Sorry about my bothering and I will try it again on another node which has more available RAM.

**Comment by ydLiu-HIT** [comment]
Hi defendant602, 
Indeed, deSALT need 73GB memory for the RdBG index which mentioned in my paper(https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1895-9). 
we also provide pre-built RdBG indexes for human(hg38), mouse(GRCm38), and fruit fly(dm6) reference genomes, if necessary, you can download directly at https://drive.google.com/open?id=1wzHfQHNL-KMcCNrz6oMXnJhxBjZImDgE (for all three references index) and https://drive.google.com/file/d/11E2j1X5jGqKNVtyNHsfPjqnu-fVBgyoi/view?usp=sharing (for human hg38 only).

Best, 
Yadong

**Comment by liufuyan2016** [comment]
I also have the issure. But I have 100Gb memory and genome is 30Mb

**Comment by liufuyan2016** [comment]
I use the ref genome size 500000 bp for test ,the error is also occured!

**Comment by ydLiu-HIT** [comment]
Can you share me the genome with a link, I will check my code and feedback to you.

**Comment by liufuyan2016** [comment]
Thanksfor your reply!
The arabidopsis genome could be download from below:
https://www.arabidopsis.org/download_files/Genes/TAIR10_genome_release/TAIR10_chromosome_files/TAIR10_chr_all.fas

**Comment by ydLiu-HIT** [comment]
Hi, liufuyan2016

I just re-run deSALT index (v1.5.1) with your genome, but no error occurred.
Please check:
1. The size of the index folder is about 2.1GB with your genome
2. You can try to run deBGA (in `src` folder) directly to see the error will come out or not. If the size of index is about 2.1GB, the process of indexing is completed.

If you have any other questions, please feedback to me, thanks.
Best,

**Comment by liufuyan2016** [comment]
Thank you. I known the reason why occure. I extract one chr sequence, and the sequence is in one line. However, I find  the deSALT index  program must be required the  sequence cutted  80bp one line.  after delai with the format , the index is ok!

**Comment by ydLiu-HIT** [comment]
Oh, I have noticed that problem, deBGA needs a cut line for the reference. I will solve that problem later. Thanks.

**Comment by ydLiu-HIT** [comment]
I have checked the source code of deBGA, the length of bases within one line should no longer than 500bp. So the genome lines should have a cut with a fixed length which shorter than 500bp.
