### ISSUE TITLE
all were the single exon for transcripts assembled by stringtie

### ISSUE THREAD

**Issue by liufuyan2016** [ydLiu-HIT/deSALT#14]
Dear.
I use the command below:
deSALT-1.5/src/deSALT aln  index/ N02.fastq -x clr -I 10000 -t 40
stringtie-2.0.Linux_x86_64/stringtie -L aln.sort.bam    -p 4 -o all.gtf.new
The data N02.fastq is about 22Gb . Howevere all   transcripts assembled by stringtie were the single exon. How to adjust deSALT to get real transcripts structure? Thanks you!

**Comment by ydLiu-HIT** [comment]
Dear,
Maybe you use deSALT with wrong command lines at `-l`. In deSALT version1.5, `-l` is the seeding kmer, `-L` is the maximum read length.  So you should change your command by:
`deSALT-1.5/src/deSALT aln index/ N02.fastq -x clr -L 10000 -t 40.`
What's more, version 1.5.1 is suggested for more readability of the usage.

This may also solve #13 
Best,

**Comment by liufuyan2016** [comment]
I use -I below  not l 
-I --max-intron-len   [INT]    maximum allowed intron length. [200000]

**Comment by ydLiu-HIT** [comment]
Okay, can you share me some reads to help me check my code?

**Comment by ydLiu-HIT** [comment]
Are you using deSALT to align reads to Arabidopsis genome? I don't know deSALT can adapt to plant genomes, because I use a scoring matrix to get acceptor and donor splicing site which based on statistics of mammal genomes.

**Comment by ydLiu-HIT** [comment]
Hi, 

Have you checked the unmapped reads are shifted by a 2048bp comparing to the true position? And are you using 'deBGA' in my github folder, because I have made some changes of deBGA in order to adapt my program(Refer to README)? If not, there will be a 2048bp shift which will cause your problem.

Best,
yadong
