### ISSUE TITLE
Hard limit on number of threads

### ISSUE THREAD

**Issue by baraaorabi** [ydLiu-HIT/deSALT#18]
Why is 48 the upper limit for number of threads?
https://github.com/ydLiu-HIT/deSALT/blob/264ab46a4fd29cc85afaf9d7acee9a1f19d4472e/src/read_seeding.c#L1582

**Comment by ydLiu-HIT** [comment]
Hi,
When deSALT was designed, considering the limitation of threads and memory of my machine, I set the limit. 
You can remove the limitation from line 1580-1584 according to your hardware environment.

Best.
