### ISSUE TITLE
deSALT does not identify exon-intron boundaries

### ISSUE THREAD

**Issue by pckorhon** [ydLiu-HIT/deSALT#20]
I ran a simple test to map a coding sequence (cds.fa) to a gene region.
In my test I know that the coding region completely and well matches to the gene region.
However, despite that deSALT correctly reports 11 exons in text output, exons in the outputted SAM file the matching exons seem random.
Easy to reproduce (deSALT v1.5):

deSALT index gene.fa GeneTest 
deSALT aln -x ccs -t 1 GeneTest cds.fa -o cds.sam

Proper approximate exon positioning can be visualised e.g. using:
cat gene.fa cds.fa > test.fa
mafft --clustalout test.fa | less

Files attached:
[cds.tar.gz](https://github.com/ydLiu-HIT/deSALT/files/4233666/cds.tar.gz)

**Comment by ydLiu-HIT** [comment]
Hi, 
I saw your reference(gene.fa) was in one line, but when RdBG-index(deSALT index) was created, the input reference genome should be cut with a fixed linewidth(less than 500 bp). Please refer to README document (Section special emphasis) or issue #12  .

Hope can help you.
Best.

**Comment by pckorhon** [comment]
Thank you, that did the trick.
