### ISSUE TITLE
deSALT alignment core dumps

### ISSUE THREAD

**Issue by pckorhon** [ydLiu-HIT/deSALT#21]
I ran another test to map a coding sequence (cds.fa) to a gene region but the program core dumped.
Easy to reproduce (deSALT v1.5):

deSALT index gene1.fa GeneTest
deSALT aln -x ccs -t 1 GeneTest cds.fa -o cds.sam

[cds.tar.gz](https://github.com/ydLiu-HIT/deSALT/files/4234447/cds.tar.gz)

**Comment by ydLiu-HIT** [comment]
Hi,
thanks for your report. I have correct the core dump and the new release source code is attached.

[deSALT-v1.5.2.zip](https://github.com/ydLiu-HIT/deSALT/files/4234985/deSALT-v1.5.2.zip)

**Comment by pckorhon** [comment]
Thank you, that release works on this one.
