### ISSUE TITLE
deSALT alignment code dump #2

### ISSUE THREAD

**Issue by pckorhon** [ydLiu-HIT/deSALT#22]
I ran more tests to map a coding sequence (cds.fa) to a gene region and the program core dumped with these sequences.
Easy to reproduce (deSALT v1.5.2 zip file):

deSALT index gene1.fa GeneTest
deSALT aln -x ccs -t 1 GeneTest cds.fa -o cds.sam
[cds.tar.gz](https://github.com/ydLiu-HIT/deSALT/files/4235604/cds.tar.gz)

**Comment by ydLiu-HIT** [comment]
Hi,
thanks a lot for helping me address some mirror bugs which hiding in the corner. Those bugs can be found by specific reads.

new scripts:
[deSALT-v1.5.2.zip](https://github.com/ydLiu-HIT/deSALT/files/4235808/deSALT-v1.5.2.zip)

**Comment by pckorhon** [comment]
Thank you, works with that version.
