### ISSUE TITLE
deSALT reference identifier missing in SAM file

### ISSUE THREAD

**Issue by pckorhon** [ydLiu-HIT/deSALT#23]
I kept running the tests to map a coding sequence (cds.fa) to a gene region and in one occasion I observed that the mapping was done correctly but for some reason reference identifier is missing in column 3 in sam file..
Easy to reproduce (deSALT v1.5.2 zip file):

deSALT index gene1.fa GeneTest
deSALT aln -x ccs -t 1 GeneTest cds.fa -o cds.sam

[cds.tar.gz](https://github.com/ydLiu-HIT/deSALT/files/4238486/cds.tar.gz)

**Comment by ydLiu-HIT** [comment]
Thanks a lot.

[deSALT-v1.5.2.zip](https://github.com/ydLiu-HIT/deSALT/files/4238656/deSALT-v1.5.2.zip)

**Comment by ydLiu-HIT** [comment]
Thanks a lot.

[deSALT-v1.5.2 .zip](https://github.com/ydLiu-HIT/deSALT/files/4238710/deSALT-v1.5.2.zip)

**Comment by pckorhon** [comment]
Thank you, that one works now as well.
