### ISSUE TITLE
deSALT core dump #3

### ISSUE THREAD

**Issue by pckorhon** [ydLiu-HIT/deSALT#24]
I found still another core dump case when mapping a coding sequence (cds.fa) to a gene region (gene1.fa).
Easy to reproduce (latest deSALT v1.5.2 zip file):

deSALT index gene1.fa GeneTest
deSALT aln -x ccs -t 1 GeneTest cds.fa -o cds.sam

[cds.tar.gz](https://github.com/ydLiu-HIT/deSALT/files/4238883/cds.tar.gz)

**Comment by ydLiu-HIT** [comment]
Thanks a lot! I haven't tested my code by CDS sequence, so there are lots of bugs at the boundary.

[deSALT-v1.5.2.zip](https://github.com/ydLiu-HIT/deSALT/files/4239143/deSALT-v1.5.2.zip)
