### ISSUE TITLE
CIGAR string includes contiguous N regions

### ISSUE THREAD

**Issue by GenomeRIK** [ydLiu-HIT/deSALT#25]
Hi Yadong,

Botond and I have found another issue with the CIGAR string representation.

The issue is that the CIGAR string is showing multiple N regions in a row.
Take a look at the offending read bam line:
71:943|0799408b-31e5-4d96-800c-91b7d0e57da9 0 scaffold_23 130155 60 1S136M59N14M135N985N704N46N56M52N152M68N51M51N353M1D107M * 0 0 GGCTTCCCAAGCTACACCTCGAGTTATTCTTTGTTTCCCCTCTCCATGATGCTCACTCCCAAATCTCTGGATCAGGACCTCTACGACGAGCTGTCGTCTCTCTGTAGGGGCCCTGTCGTGCTCAACGACGACCCAGACTTCGTAAATTATGCGACGACATTATCCATACGACGGTTGAACAATTCAGCAACACTCCGCTTGGTTGCACGTGGCTTTTCGAATTGGCGGGAGGCGCCGTTGGGGAGTTTACGGATTCCGTGGTCCCGAAGGCTCAAAGGGAAGCGTTGTTCAACATCGTGGCACTCCACCAGTGTGAGATGGATGCCAATGATGATCGGTGCATCGATTCTGCTGAGGAGTGGATTGCAGGGACCTTGAAGCCCGTACACATCGGCGACGCATTCCCTAGCTTCTTTGGAAGGCATGAGATTCCAGAGCGCATCAAAGCTTCTTTCGGGGTGAACTGGGACCGCTTGGTGGAGGTTAAGAAGAAATACGACCCCAAGAACATTTTCAGCAATAGCTTCTGGCCTTTGAATGAACATGGTGAAATAGTCGACCCCCGCACCCATGAGCCATCCACCCCAGGATATCTTGACTCTTGGCAGAGGGCAAAGATCTATGGGTAGATTGTGTTCACCTTCCTGTGACCTCGTCCCTCTCAGCCCAGGCTCGCCGTCTTCACCGCTCTATCCATCCCTTCACTCATCTACTCGATCTCGCTTAGCCCTGTACATAT

If you look at the cigar string, there is something very weird:
1S136M **59N** 14M **135N 985N 704N 46N** 56M **52N** 152M **68N** 51M **51N** 353M1D107M

I made all the N values bold. Notice the region 35N 985N 704N 46N. 

As far as I understand, unless there is another feature between the N's, the N's should be represented as a single region. 

I will let Botond submit the files for you to be able to recreate the bug. 

Thank you,
Richard

**Comment by ydLiu-HIT** [comment]
Hi Richard, 
Thanks for reporting the problem of contiguous N regions, I have solved the problem and attach the revised version of deSALT

[deSALT-v1.5.3.zip](https://github.com/ydLiu-HIT/deSALT/files/4303305/deSALT-v1.5.3.zip)

**Comment by HegedusB** [comment]
Thanks again both of you the quick help. I will try out the modified version and report the result. 
Botond

**Comment by HegedusB** [comment]
Hi Liu,
The new version is working fine with this read set. I am going to test it with a larger read set but I hope there wont be any problem. 
Thanks for the help,
Botond

**Comment by baraaorabi** [comment]
I had a similar issue in v1.5.2 but where two `N` regions are separated by a single `D` operation:

12S9M1I3M1I12M2D25M1I8M4D12M1I21M1I3M1I4M1D16M1D3M2D2M1D8M1I10M1I2M2D2M2D31M1D24M2D22M2D3M3D24M1D2M1I2M2D10M1D7M3D3M4D3M1I5M2D5M1I6M1I4M1I2M2I1M1D4M3D5M1D4M1I2M3D10M2D4M1I12M5D11M1D7M2I1M1D4M1D5M1D1M3I2M1I6M1I1M3D6M1D6M2I5M1I7M1I16M1I2M1I6M1D7M1D6M1D9M1D8M3D5M2D1M1D1M1D6M1D18M1D7M1I30M1I6M2I15M1D10M1I6M1D2M3D11M2D5M2D2M2D1M1D19M3D27M3D3M1I11M1D12M1D18M1D6M2D5M2I1M1I3M2D7M2D17M1D8M3D7M1D5M4D16M2I3M3D11M1D16M1D3M1D4M1D3M1D1M1D40M1D26M1I25M1I2M2D6M1I13M3D12M1D3M1I1M2D5M1I4M1D5M2D19M1I19M1D7M2D8M1I14M1D7M1D3M1D2M1D4M1I4M1D14M1I5M2D1M1D2M4D24M2I18M2D2M1I7M2D4M1I15M1D15M1D10M2I4M1D14M1I4M1D6M1D5M3I1M1I13M9D5M1I7M1I12M1I7M1I4M2I11M1I28M1D10M3D15M2D14M4D10M2I5M4D5M2D9M1I4M2D2M2D26M1I6M1I6M1I8M1I5M2I2M1I8M3I14M1D5M1I6M5D20M96493N12M2D4M1I10M1D20M2D5M2D5M1I5M1I4M1I10M1D7M1I9M1D2M4D2M2D10M1D3M2I9M1D8M2D5M1I3M42602N18M2I15M2D1M1D13M1D5M2I8M5D7M1D19M1D3M1I12M1D4M25275N1D6M1I16M1D4M1D19M1I4M2D7M2D5M4D7M1D13M1I10M1D6M2I1M1I14M1I21M1I12M1D9M1D5M1D8M1D7M1D12M1D28M1D6M2D12M2I2M3D7M1D7M1I14M
**10481N2D1513N**
6M1I7M2D5M1D5M4D2M1I4M1I13M1D1M1D17M2D29M1I7M1I1M1I11M2D11M1D12M1D2M2D14M1D15M3D8M3D6M1I3M1I14M1D9M47S


Has that been resolved too in v1.5.3?

**Comment by ydLiu-HIT** [comment]
Hi, 
I am sorry for replying to you so later. I am not sure the previous version can resolve the problem you have mentioned. But in the current version, I have added some function in my program to avoid the situation like "NDN" bad cigars. The new version was attached. 
Thanks for your report and hope you can test my new version. If there are any questions else, please let me know. Good luck to you.

Best,
Yadong

[deSALT-v1.5.3.zip](https://github.com/ydLiu-HIT/deSALT/files/4507418/deSALT-v1.5.3.zip)

**Comment by baraaorabi** [comment]
Awesome! And thanks for updating the bioconda recipe
