### ISSUE TITLE
exon length distribute?

### ISSUE THREAD

**Issue by luckylyw** [ydLiu-HIT/deSALT#26]
Hi!

 I have read your article about desalt. After I run desalt, I want to know how did you statistics the distribution of exon length? Is there any scripts of existing tool?

It is very important for me. Look forward to your reply!!!

**Comment by ydLiu-HIT** [comment]
Hi, 
I statics the distribution of exon length for real Pacbio/ONT reads alignment SAM by an in-house script `Eval_real_data.py` at https://github.com/ydLiu-HIT/deSALT/tree/master/evaluation .  More details can be found at https://github.com/ydLiu-HIT/deSALT/blob/master/evaluation/data_evaluation.md

Best

**Comment by luckylyw** [comment]
Thanks for you quick reply. I took item.getlength() in eval_real_data.py as the length of exon. By the way, dose the exon'length represent the length of the 'read mapping' or 'exon length in gtf'?
look forward to you reply. 

sincerely

**Comment by ydLiu-HIT** [comment]
Hi,
That represents the length of exon in gtf.

Best

**Comment by luckylyw** [comment]
Does this exon have to be included in the raw reads?

**Comment by ydLiu-HIT** [comment]
Yes, all the exons calculated were included in raw reads, these exons are aligned to GTF exons by read alignment.

**Comment by luckylyw** [comment]
Hello， when I use Eval_real_data.py to evaluate the sam file , I met this error .

(02:01:17.800968) Loading and processing annotations file ...
(02:01:46.125165) Loading and processing SAM file with mappings ... Traceback (mos
  File "Eval_real_data.py", line 745, in <module>
    eval_mapping(sam_path, annotation_path, exon_len_file)
  File "Eval_real_data.py", line 319, in eval_mapping
    Final_result.append(eval_mapping_part(chro, exon_len_file))
  File "Eval_real_data.py", line 581, in eval_mapping_part
    expressed_genes[annotation.transcriptname][item_idx] += 1
IndexError: list index out of range

**Comment by luckylyw** [comment]
Also， i have met this problem when i run eval_real_dat.py

(03:43:44.105160) Loading and processing SAM file with mappings ... 
Traceback (most recent call last):
  File "Eval_real_data.py", line 734, in <module>
    eval_mapping(sam_path, annotation_path, thread)
  File "Eval_real_data.py", line 325, in eval_mapping
    report_dict[chro] = Final_result[i].get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IndexError: list index out of range

**Comment by ydLiu-HIT** [comment]
Hi, 

Could you tell me your command lines, the version of python, and the format of the annotation file(GTF or GFF).  If necessary, you can support part of alignment files and the annotation for me to look into the error. Because that is an in-house script,  there may be some conditions that I didn't consider when encountering such as different annotations formats and others.

Best!

**Comment by luckylyw** [comment]
Hi,
    Sorry for late reply. I am preparing my graduation paper recently.
the command is: python2 Eval_real_data.py ./mouse_saqnti/raw_aln.sam ./mouse_saqnti/Mus_musculus.GRCm38.87.gtf 5 > ./mouse_saqnti/eval_mouse_sa_raw_result.txt 1>./mouse_saqnti/mouse_sa_raw.log
the version of python is : Python 2.7.12
the format of GTF is: 
`#!genome-build GRCm38.p5
#!genome-version GRCm38
#!genome-date 2012-01
#!genome-build-accession NCBI:GCA_000001635.7
#!genebuild-last-updated 2016-12
1	havana	gene	3073253	3074322	.	+	.	gene_id "ENSMUSG00000102693"; gene_version "1"; gene_name "4933401J01Rik"; gene_source "havana"; gene_biotype "TEC"; havana_gene "OTTMUSG00000049935"; havana_gene_version "1";
1	havana	transcript	3073253	3074322	.	+	.	gene_id "ENSMUSG00000102693"; gene_version "1"; transcript_id "ENSMUST00000193812"; transcript_version "1"; gene_name "4933401J01Rik"; gene_source "havana"; gene_biotype "TEC"; havana_gene "OTTMUSG00000049935"; havana_gene_version "1"; transcript_name "4933401J01Rik-001"; transcript_source "havana"; transcript_biotype "TEC"; havana_transcript "OTTMUST00000127109"; havana_transcript_version "1"; tag "basic"; transcript_support_level "NA";
1	havana	exon	3073253	3074322	.	+	.	gene_id "ENSMUSG00000102693"; gene_version "1"; transcript_id "ENSMUST00000193812"; transcript_version "1"; exon_number "1"; gene_name "4933401J01Rik"; gene_source "havana"; gene_biotype "TEC"; havana_gene "OTTMUSG00000049935"; havana_gene_version "1"; transcript_name "4933401J01Rik-001"; transcript_source "havana"; transcript_biotype "TEC"; havana_transcript "OTTMUST00000127109"; havana_transcript_version "1"; exon_id "ENSMUSE00001343744"; exon_version "1"; tag "basic"; transcript_support_level "NA";
1	ensembl	gene	3102016	3102125	.	+	.	gene_id "ENSMUSG00000064842"; gene_version "1"; gene_name "Gm26206"; gene_source "ensembl"; gene_biotype "snRNA";
1	ensembl	transcript	3102016	3102125	.	+	.	gene_id "ENSMUSG00000064842"; gene_version "1"; transcript_id "ENSMUST00000082908"; transcript_version "1"; gene_name "Gm26206"; gene_source "ensembl"; gene_biotype "snRNA"; transcript_name "Gm26206-201"; transcript_source "ensembl"; transcript_biotype "snRNA"; tag "basic"; transcript_support_level "NA";`
the sam file i use: 
`26      0       7       141476415       60      71S16M1D8M2D15M1D19M1D1M6008N27M3D31M1I2M2D15M6985N5M1I7M2D34M3D2M3D1M2D22M1D4M3D1M1D3M3I1M1D32M2I25M1D12M3D23M1018N21M2D16M1D35M735N54M3D45M100N15M4D3M1I17M2D5M2D9M1I13M1I32M1D29M74N2D30M1D51M821N44M1D33M1D44M1D10M1D26M1I5M2D13M1D9M1D16M2D11M2I9M1I3M3D28M1D5M2D9M1D19M2I3M5D59M1D10M2D48M1I7M1D86M1D14M40S       *       0       0       CATGCTTCGTTCAGTTGCAGCGTACTCTTGCCTGTCGCTCTATCTTCGGCGTCTGCTTGGGTGTTTAACCTCTGTGAGTCACTGTGGCTGGGATCGAACAAGATCTGGGCGAAGACTGCTGGTGGCCAGGAGCTGAAGCGCTGCAGCATGGCGCGCGGCCTCCAGGGCGTCAAGTACCTCATGTTCGCGCTAGCCTGCTCTTCTGGCTGGGCTGGCCGTTGTCCTGGGTGTTGGCATCTGGTTGGCTGCCACAGGCTGCCACCTTATCGTCCTCATTTCATCGCGGTAACACCAACCTGCTCATCGTCACCGGGACCTTCGTCGCATGGCCATCGGCTTCGTGGGCTGCGTGGGGCCCTCAAGAACAAGTGCCTACTGCTCACTTTCTTTGTGCCACTGCTGCTAATTCCTGCTGGAAACCGCATTGCTGTACTCTTCTTTGCCTACAGTGACAAGATTGACAGTTATGCCCAACAAGACCTGAAGAAGGGCCTGCATCTGTATAGCTGAGGCAACGTAGACTCCACCAATGCCTGGAGCATCATCCAGACTGATTTCCGATGCTGTGGAACAGATTACACTGATTGGTTTGGTGTAATGCCACTCCGTGTGCCTGACTCCCTGCTGTCACAGGTTCAGTGATAGCAATGGGTCCATGAACCTGGTACCTGGTGGAAGTCGCTGTTATGAGACAGTGAAGGCCTGGCTCCAGAGAACCTGCTAGCTGTGGGCATCTTTGGACCATGCACGGCACTGGTGCGAATTACAGGCCTCACCTTCGCTATGACCATCTGCTGCCAGGTGGTAAGGCGGACACCTACTGTGCATAGGTCTCACAGCTCTGCTTCTCTGCCAAAGGACCCGCCCACGGGAAGGAAGATGTCAAACCCGCTCCCCTGCAGGACTGGTGTTCTGCTGAGATACAGGGAAGAGCTGGAGCCAGAGCACCAGCATCCATCCCTGCCTGAGGGCACTTTCTGCTTGGTGTGGCAGACACCGAACTATAGAGTTGGTGCCAATGGCGCAGGGCTAGAGCCCAGGGAACTTTGACGCACATATCCATATATACCTTCCAGTGTTCACACAGGATGGGGTTCCCAGCCTTGCATGGTTGTAGGTTGGGGTGACCCAATCTGCTCAAGGCCCACGATGATCTTGGTGCTCCAGGCAGGAACCAGGTCCATGATCCACATTCCATGACAGTGTCGTGGTTCCAGATGCATCTTAATAAAGTGTGTGAGCAGACTGTGGGTCTTGCCAACACACAAGGTTGTACAGCCAAAGGTTAAACACCCAAGCAGACGCCGCAATATCCAGCGT        *       NM:i:140        ms:i:848        AS:i:624        nn:i:0  ts:A:+  tp:A:P  cm:i:141        s1:i:650        s2:i:0  de:f:0.0819     MD:Z:16^C8^AG1C0T10A1^T19^A28^GCT33^TC1A22T2^GG34^CAG2^AAA1^TT12A9^C4^CTT1^T4^T0G56^A0T11^AGG33T0G9^GT0G12G2^A0C9G72G2A0C1^CAG8G1G1C0T46^GTTT0C19^GA3A1^AC31T0G0G0A13T0G4^T1A27^CC30^G31T0G16A0G3C0T0G23G1A12^A33^C44^C10^C28G2^GG13^G9^C16^CA23^GCA9A0G17^A5^CA1C7^A2G19^TTTTT59^C10^GC0A1G4G40G6^C86^A14      rl:i:0`

**Comment by luckylyw** [comment]
In the result file of eval_real_data.py, What does the specific output represent? Such as "(**)Number of samlines cover_All_exons / cover_Some_exons/ equal_one_exon / cover_No_exons"

**Comment by ydLiu-HIT** [comment]
Hi, 
I suggest you transfer the GFF3(or GTF) format to a simple GTF format by `gffread` (install by `conda install -c bioconda gffread` or https://github.com/gpertea/gffread) with command `gffread Mus_musculus.GRCm38.87.gtf -T -o new.gtf` and then re-run the evaluation command with the new GTF annotations. I attach a new `Eval_real_data.py` and it's dependency `Annotation_Load.py` at the bottom.

cover_All_exons: the alignment of the read cover all exons of one transcript in annotations, which show that the alignment was well good(that is, the read is full-length transcript sequencing read and map to the right annotation);
cover_Some_exons: the alignment of the read cover parts of exons of one transcript in annotations, which show that parts of the read can't align to its corresponding transcript;
equal_one_exon: the alignment of the read has one mapped part(the part between two 'N' cigars) can map to a transcript exon well, that shows the read may come from the transcript;
cover_No_exons: the alignment of the read can't map to any transcript in annotations, which meams the read map to the wrong place of the genome or there is a new transcript which not present in the current annotations.
In general, when most of reads are from cover_All_exons or cover_Some_exons, the alignment results are much better I think.

Best!

[Eval.zip](https://github.com/ydLiu-HIT/deSALT/files/4354951/Eval.zip)

**Comment by luckylyw** [comment]
Thank you for your reply.

 I've probably understood what it means. But there is a problem here. The sum of different exon cover cases is greater than the total number of readings? Why is that? 
```
(**)Number of alignments (total/with CIGAR) = 714083 / 714082 / 1.0000
    (**)Number of samlines cover_All_exons / cover_Some_exons/ equal_one_exon / cover_No_exons = 677087 / 685464 / 466053 / 28618
```
           Also, what does intron bases (overlap, more, out) in introns represent?

**Comment by ydLiu-HIT** [comment]
In the in-house benchmark script, `#cover_some_exons + #cover_No_exons = #readings`, cover_All_exons is a part of cover_Some_exons.

If the alignment part between two 'N' cigar options can't map to any transcripts in the annotations, I consider the part is out of the coding region as 'out' (intergenic); if the part located in the region of one transcript but can't map to any exon of the transcript, I consider the part is intron parts which called 'more'; If the part overlapped partially with one exon and some bases are outside the exon, I consider the outside bases as 'overlap'.  
In general, I want to show where are the uncovered bases come from (intergenic, intron or outside bases due to incorrect splicing site).

Best!

**Comment by luckylyw** [comment]
Thank you so much. You really helped me a lot!!!!
