### ISSUE TITLE
Question: linewidth

### ISSUE THREAD

**Issue by hengjwj** [ydLiu-HIT/deSALT#27]
Hi,

I'm unsure about the special emphasis on linewidth. 

Could you give a bit more detail:
1) what is linewidth?
2) what would be a good number to change it to?
3) considerations and implications of (2)?

Thank you.

**Comment by ydLiu-HIT** [comment]
Hi, 
The reference sequence should be cut with a fixed length for each line (the length should be less than 500bp).
example: If you have a reference whose length is 1000bp, you shouldn't present the sequence in one line with 1000bp, you should use a cut (eg. 100bp) to present the sequence in 10 lines which each line contain 100bp.

Any cut less than 500bp is ok. If your reference present in one line, you can change by: 
'python changelinewidth.py your_genome.fa changed.fa linewidth(e.g. 80)'

Best!
