### ISSUE TITLE
index interrupted

### ISSUE THREAD

**Issue by BeatrizdeToledo** [ydLiu-HIT/deSALT#28]
Good afternoon. I was trying to build my own index file from mouse ensmbl primary asssrembly .fa file, but at somepoint it stops, I am not sure what is wrong. 
deSALT index GRCm38_80_width.fa /group/index_desalt/ 
I changed the width to 80 as advised

"begin wrtting hash and kmer array and offset on unipath into file 2087305975
begin writing info about size of index files
deleting div temporary index file folder
rm: cannot remove `/group/calegari_beatrizepi/index_desalt/div': Directory not empty
finish index building
Program finished

[desalt_index] Indexing undoing, deBGA index exit abnormally. "

**Comment by BeatrizdeToledo** [comment]
Another option would be to use the debga file of your github, but when I use it the .sam output has the chr notation, and I would like to have the numeric notation of the chromosomes

**Comment by ydLiu-HIT** [comment]
Hi,
I don't know why you get strange output. In fact, you have finished the index building, but the program encounters an error when the program wants to delete the temporary file and folders in your system.

I have attached a new version that has addressed some bugs which pushed by other users recently. You can download it and then retry one of the following to finish the program:
1. (Index mode) ./deSALT index reference.fa Index_route,  (Align mode) ./deSALT aln Index_route read.fa
2. (Index mode) ./deBGA index reference.fa Index_route,  (Align mode) ./deSALT aln Index_route read.fa

Good luck
Yadong

[deSALT-v1.5.3.zip](https://github.com/ydLiu-HIT/deSALT/files/4507522/deSALT-v1.5.3.zip)

**Comment by BeatrizdeToledo** [comment]
Good afternoon,
The new version was installed and the message "[desalt_index] Indexing undoing, deBGA index exit abnormally." does not appear anymore. So I imagine the problem was solved. but still this message appears "deleting div temporary index file folder
rm: cannot remove `/group/calegari_beatrizepi/index_desalt/div': Directory not empty"
Is this normal?
Here are the last lines

begin wrtting hash and kmer array and offset on unipath into file 2087305975
begin writing info about size of index files
deleting div temporary index file folder
rm: cannot remove `/group/calegari_beatrizepi/index_desalt/div': Directory not empty
finish index building
Program finished
[desalt_index] Done!
[Main] Real time: 5265.192 sec; CPU: 0.005 sec, Memory peak: 0.00 GB
