### ISSUE TITLE
Strand information

### ISSUE THREAD

**Issue by gmoneyomics** [ydLiu-HIT/deSALT#29]
Hi. I am using deSALT to align nanopore cDNA and feeding the bams into StringTie2 for assembly and quantification. StringTie requires strands information in the bam file. Is there a way to add strand to the bam? Thanks!

**Comment by ydLiu-HIT** [comment]
Hi, 
I don't know about the strands information you pointed, is it the aligned read come from forward strand or reverse strand? If necessary, you can give me an example of the information in bam file. If feasible, I will add it to deSALT for you.

Best 
Yadong

**Comment by gmoneyomics** [comment]
Hi Yadong,


Thank you for getting back to me.  We normally use the XS tag in the bam alignment, in the way that Hisat2 (or TopHat) reports it. Here is a description for it:

XS:A:<A>


Values of + and - indicate the read is mapped to transcripts on sense and anti-sense strands, respectively. Spliced alignments need to have this field, which is required in StringTie.
We can report this field for the canonical-splice site (e.g. GT/AG, GC/AG ), but not for non-canonical splice sites.



For instance, if the alignment will produce an intron starting with a GT and ending with an AG the tag XS:A:+ would be added to the bam entry. If it is starts with CT and ends with an AC then it will have the XS:A:- tag.

Thanks!

Ariel

________________________________

**Comment by ydLiu-HIT** [comment]
Hi, 

I am sorry to reply to you later. I have released deSALT-v1.5.4 which has added "XS:A" tag, you can download directly and test the code. If there have any question, please tell me.

Best, 
Yadong

**Comment by gmoneyomics** [comment]
Hi Yadong,


Thank you very much!

________________________________
