### ISSUE TITLE
deSALt is crashing again and gain after second phase of mapping?

### ISSUE THREAD

**Issue by unique379** [ydLiu-HIT/deSALT#33]
Hi 
I am trying to use 1D nanopore sequencing file to map against reference genome but always deSALT crashing **([kfree] The end of a free block enters the allocated block.)** once second phase of alignment starts. Please take a look logs and command that i used. By the way I am using snakemake to submit the job.
Please help.

`/stornext/snfs5/next-gen/scratch/rupesh/Apps/envs/NanoPacks/bin/deSALT aln -o /space1/tmp/$PBS_JOBID/SID102054_cDNA_101819_desalt.sam -t 4 -f /space1/tmp/$PBS_JOBID/SID102054_cDNA_101819_Temp -x ont1d /stornext/snfs5/next-gen/scratch/rupesh/ProjectFritz/database/deSALT_index /stornext/snfs5/next-gen/scratch/rupesh/ProjectFritz/reads/reports/NanoFilt/SID102054_cDNA_101819.highQuality-reads.fastq.gz`

`[Main] deSALT - De Bruijn graph-based Spliced Aligner for Long Transcriptome reads
[Param-INFO] deSALT parameters:index-kmer:22	seed-lmer:15	hash-kmer:8	thread:4	strand_diff:20	identify junction:both_strand
[Phase-INFO] Loading Index and Reads
[Phase-INFO] Seeding and Chaining Phase (first-pass)
[Skeleton-generation] Generating skeletons of 655350 reads, total 607024114 bases in 672.023093 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 613066166 bases in 690.591843 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 615758850 bases in 819.567225 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 612574330 bases in 685.050524 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 627007039 bases in 754.055307 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 620968613 bases in 696.275752 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 625773740 bases in 704.642594 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 618965611 bases in 738.996169 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 626865823 bases in 708.907906 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 640674566 bases in 742.101829 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 629465121 bases in 747.530073 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 633279914 bases in 718.192956 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 639394149 bases in 777.490834 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 644136451 bases in 739.439812 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 655512017 bases in 767.843477 seconds
[Skeleton-generation] Generating skeletons of 655350 reads, total 616605369 bases in 802.252768 seconds
[Skeleton-generation] Generating skeletons of 212445 reads, total 196972833 bases in 220.198870 seconds
[Phase-INFO] Total 10698045 reads were processed in 11985.197 seconds (first-pass)
[Phase-INFO] Refined Alignment Phase (second-pass)
[Phase-INFO] Exons inference by skeletons of all reads
[Phase-INFO] Inferring total 458675 isolated regions (pseudo-exons) after merging and filtering
[Phase-INFO] Refining pseudo-exons by scoring matrix
[Loop-ProcessReads] The 0st loop of refined alignment procedure with 655350 reads......
[Loop-ProcessReads] Aligned 651266 reads to genome, and confirmed total 71837 exons' strand in 1153.297927 seconds
[Loop-ProcessReads] The 1st loop of refined alignment procedure with 655350 reads......
[Loop-ProcessReads] Aligned 650974 reads to genome, and confirmed total 89164 exons' strand in 928.821535 seconds
[Loop-ProcessReads] The 2st loop of refined alignment procedure with 655350 reads......
[Loop-ProcessReads] Aligned 651003 reads to genome, and confirmed total 99664 exons' strand in 902.596707 seconds
[Loop-ProcessReads] The 3st loop of refined alignment procedure with 655350 reads......
[Loop-ProcessReads] Aligned 650805 reads to genome, and confirmed total 107778 exons' strand in 891.536300 seconds
[Loop-ProcessReads] The 4st loop of refined alignment procedure with 655350 reads......
[Loop-ProcessReads] Aligned 650839 reads to genome, and confirmed total 114369 exons' strand in 911.941630 seconds
[Loop-ProcessReads] The 5st loop of refined alignment procedure with 655350 reads......
[Loop-ProcessReads] Aligned 650480 reads to genome, and confirmed total 119720 exons' strand in 904.910205 seconds
[Loop-ProcessReads] The 6st loop of refined alignment procedure with 655350 reads......
[Loop-ProcessReads] Aligned 650338 reads to genome, and confirmed total 124348 exons' strand in 888.339863 seconds
[Loop-ProcessReads] The 7st loop of refined alignment procedure with 655350 reads......
[Loop-ProcessReads] Aligned 649973 reads to genome, and confirmed total 128435 exons' strand in 895.199659 seconds
[Loop-ProcessReads] The 8st loop of refined alignment procedure with 655350 reads......
[Loop-ProcessReads] Aligned 650070 reads to genome, and confirmed total 132401 exons' strand in 873.805485 seconds
[Loop-ProcessReads] The 9st loop of refined alignment procedure with 655350 reads......
[Loop-ProcessReads] Aligned 650123 reads to genome, and confirmed total 135836 exons' strand in 931.015882 seconds
[Loop-ProcessReads] The 10st loop of refined alignment procedure with 655350 reads......
[kfree] The end of a free block enters the allocated block.
/bin/bash: line 1: 19611 Aborted                 /stornext/snfs5/next-gen/scratch/rupesh/Apps/envs/NanoPacks/bin/deSALT aln -o /space1/tmp/$PBS_JOBID/SID102054_cDNA_101819_desalt.sam -t 4 -f /space1/tmp/$PBS_JOBID/SID102054_cDNA_101819_Temp -x ont1d /stornext/snfs5/next-gen/scratch/rupesh/ProjectFritz/database/deSALT_index /stornext/snfs5/next-gen/scratch/rupesh/ProjectFritz/reads/reports/NanoFilt/SID102054_cDNA_101819.highQuality-reads.fastq.gz`

**Comment by ydLiu-HIT** [comment]
Hi,

I am sorry, I cannot find out the error without any other read information, so I need some reads around and you reference genome to run the command and detect the error.

Yadong

**Comment by unique379** [comment]
Hi

Reads and ref looks like this... **i hope its not a problem of chr as i have primary chr, unplaced and unlocalized in genome.**

`@ffbba9eb-7700-489e-99ed-ed7d2f929e78 runid=8edba1a284814aa5d76bf6436efe9bb32fc8b6c3 read=9 ch=2043 start_time=2019-10-18T20:55:51Z flow_cell_id=PAE07891 protocol_group_id=SID102054_cDNA_101819 sample_id=SID102054_cDNA_101819
GTATACTTCCCCCGTTCAGTTACCTGGAAACTGGGTGTTTATGGTTGTCCCTTCACCGTGACAAAAGTTGTCGGTGTCTTTGTGTTTCTGTTGGTGCTGATATTGCTGGGGATCATGTGCTACTGGTATAAAGTTCTGGCCCTTCTACATAAAAGAAGATGGCGACCAGGCAAGTCCACAGTACCGACAACTTTCTTGTC
+
'+*%%###%%&&+.1/0,3**&%#$#$$%$$(&'/50554.+-+$$$%&-&&(&$%'.55,(%%()7<;,.7%&5.;8997697?=5676787:99;9>8000168;.-6@:292'&&%1+*,..055,>A3>283-&(-0/(1//)*$(''&&%()*),%('+(%*',.+#'%((6%&%&$'&(-/512>EFF@D=41'
@70402786-e42d-4006-bc9f-7764eb5309c4 runid=8edba1a284814aa5d76bf6436efe9bb32fc8b6c3 read=7 ch=925 start_time=2019-10-18T20:55:51Z flow_cell_id=PAE07891 protocol_group_id=SID102054_cDNA_101819 sample_id=SID102054_cDNA_101819
CAGTGTACTTCGTTCAGTGCTTCTCGATTTAGGTGTTGTGGATATCATACCTACCGTGACAAGAGAGTTGTCGGTGTCTTTGTGACTTGCTGTCGCTCTATCTTCTTTTTCTTTTTTTTCTTTGGGACAGTGTCTTCTCTGTTGCCCAAGCTTGGAGTGCAGTGGTGTCAGCACGGCTCACTGTGGCAATATCCTTTCAACAGAAACACAAGACACCGACAACTTTCTTAT
+
##$$#%%./.''20+%$'##%'$%&$%&''$205/11&$%()%&$%$%$%$)*/.19@ECCA80('<2@>6B,1:=@;IH6,-68112++2.@A<E87;<B8E?+:;C??:@>GB?:;8588-%&04//8;861&&(7291,/#%%%$&'(((*+)9;4,,8>:*4(*9;2::((-:9=57?,%%&+$$((+#(#%'%%%%%+02/0-+%*)++'$$%',119;;9*00')`


`.
├── deSALT_index.o2674010
├── gencode.v33p13.primary_assembly.annotation.exon.gtf
├── gencode.v33p13.primary_assembly.annotation.gtf
├── genome.info
├── GRCh38.v33p13.primary_assembly-bs.umfa
├── GRCh38.v33p13.primary_assembly.dict
├── GRCh38.v33p13.primary_assembly.fa
├── GRCh38.v33p13.primary_assembly.fa.fai
├── hg38RefSeq.bed12
├── index_deSALT.sh
├── N.sta
├── ref.seq
├── unipath.chr
├── unipath_g.hash
├── unipath_g.kmer
├── unipath_g.offset
├── unipath.pos
├── unipath.posp
├── unipath.seqb
├── unipath.seqfb
└── unipath.size`
