### ISSUE TITLE
Segmentation fault (core dumped) with SIRV gtf for genome.info (--gtf)

### ISSUE THREAD

**Issue by opplatek** [ydLiu-HIT/deSALT#36]
I wanted to test deSALT on [SIRV ](https://www.lexogen.com/sirvs/sirv-sets/) direct RNA-Seq ONT data with the `--gtf` option. I made the genome.info file (`python Annotation_Load.py sirv.gtf genome.info`) and added the output to the `--gtf` option. The alignment crashed with **Segmentation fault (core dumped)**. 
I tried to leave out individual options but the `--gtf` option seems to be the problem. 

The whole SIRV reference and gtf is available [here](https://www.lexogen.com/wp-content/uploads/2018/08/SIRV_Set1_Sequences_170612a-ZIP.zip).

I am not sure if the cause might be the fact SIRV exons don't always follow canonical bases around the edges. 

The whole used command:
`python changelinewidth.py SIRVome_isoforms_170612a.fasta sirv/genome.fasta 500
deSALT index sirv/genome.fasta sirv/genome

python Annotation_Load.py SIRVome_isoforms_C_170612a.gtf sirv/genome.info
    
deSALT aln \
    -f $sdir/ \
    --thread 6 \
    -p 0.99 \
    -l 14 -s 2 -x ont1d \
    --gtf sirv/genome.info \
    --noncan 0 \    
    --output deSALT.sam \
    sirv/genome \
    input.fastq`

Here are a few fastq lines:
`@99dc5a60-bd88-4a25-a6f8-495284333bef
GTTAGAGCAGTTTATCGGGTGGTAGGTATTACATCTATCTACTTCAAAACGAGCCACAAGCATTGCTTTGTAAAATTGTTGAAGGTAACTTGTAAAGCCGAACATGAACGATGGATATTGGTAGACCGGGGAAGACTTCAACGTTTCATCTCAAAGAACACACTGAAGGGAACGGTGTAGGTTCGGTGAGTCCGGGACTCTAGGTGTCCATGTCGGAGACCTCAGTGGGTGACGTCCATAGTATAGAAAGCATTTCCCTCCCACCCCACCTCCCCCACACCCATCCCCCACCATCATCATATCCATCAACCCCCATCACCTATACTTCCTAAACTTCC
+
;/=A@B?;%+&(%%'&,73:>8A075-*,&#(*)*,1-%**&+2248682*#''(#($&.,)-)$)..866666&4:56-34;;A=:?:80*)04<)-.4:62-007??6;3616-"'&/)273;/(#$$#$.200&&+*)$/621%$%$%$#%:7/).12--7;7:6=;DD742=946:9)/.0.7++4$/810,:4%#*%<>;348:4*31./)243,,*&337445:=>21*+&%+6+&'+0120)%$#'&&.34&&*%#&.,-%))$%+*+)#&#%&&$$*.14*"+%%&%$&'%'$(-,+($##%)))&##&#)%&('#$$%..5845,)2/&
@9840fd98-af12-4ae4-aef5-077b12b405d9
CTCGCTGCCATTCCAATTGCTCGTCATGGACTCCACTTTAGACGACCCGATGAAGCTGGAAGTCTGACACACTGACATCTGCTTGTGGCAATCGTTGTTGGGTGGCCACTTTGACTCGACGTTTCACGAACATACGATGGTTAGTTCTCTACTATTCTAATGGCTTGTTTCGCAGAATCTGTATTTAGACGTAACAATAGAAATAATCTTTTTGGACATTGATTAGATTCTTTAATAATAGGTTATCTACCAAGTTGACGTTTTCACAAGTTGTTTTAAACCGACTTTTTGATGTGTTGTAGTTATTACAGCTGAAAGATGACGCGACTAGAGCCGCGGCGTGTCAAACTTTGCATGCCAGTCGTGGCAACAGCGAGTCAGGTTTGACTAGCCTATGTTAATTTGCTCGCTATATAAGTCAATAACTTTATTCCGTCAAAAAAGACTCCACACAACCCATTTTTCATTTTTATATTCATATTTTTTATTTCTTTCTTCTTTTTCTTTTAACCCCCACATTTATCCCCTCAAACTCC
+
))(%&15787;9<>>?>6592>9::2,:8>:1$/+.)&8+:09535138?3@?D@<9/(2113-8=54%'%*24,.%*)%%''9;5><8954:7::;,)&''+($5;81-%872(*,8@5426'*9>>>;;2*'089C;9<6+/*(&*'%$+82+-'4=:==;2195+(*))27/;<<98:61<6?;=;65454482)--/:6+;8*$%%&-=41?>;/42.(488;?7#&0;;6>;97*/.'%%&#&&.3-3:6E7B..298$2:=<C>604.7(+99==36?8/'.78:A><=)19>2:3?<:;%'79>4=@BAE<<56:21&&%),,2/*2.)$3*43;:858:<-%'321)**:<3;563#%$$$#.$2/4/-,.24400&&-8;02366?>9/;97/1.,4$$$&/5.$40..;7<?89:7;(,-+&,)*0-461-(%#/($&)&*)%$$&($%-)+*($%)%()-&/()&$&)#+**+**.0&&''%&$%'$'$+&($''%&&%$%$%%###$%%$*'00&&&'$$$$'.
@ee67504e-e7f5-4c0d-85c9-3fcf98b9e5ed
GAGATTTACGTTGCTGACAAGAGGATGATGTGACGTAAGGGTCTTGAGTGAGACATATGAGGCTAACGGCGTCCATTAATACCATGTGGTGTAGAAAGCGTCTTTGACATGTGTATGGATGTTTTTGCAATGCTTTGTTCATTGGGGTTGGTTTTGACATTGTTCGTTCAGTACTTTATAGTACTTCGACTACCTTTTCCATTTGACCGACTTTTAGCGAAAGCCATTTGATGAAGGTAGCGACTTTACCCGTCGTTCCCAAATTAGTAAAAAAATCCCATCCATCCATAACCATCCCTATATCTTCATATTCCAACATTTTATCCGCCCTTCATATCCCATTTATTCCAATTCCC
+
8<;=7,-9C5=86496*,'99=69:<6&''48<;6%23764.(%$#,9?;B622$%'014-2655330//1-4/,+'(%.,-2,')782'%7%0)55=43'%+'755-'(&&&2%3,(.))+3/48:355(%&&%672*+024720/.02.81((+*5,'::31((&03773&'(&*)%.33;5+7.067/55*&(71277+%5300.58,'63:<:995>@?;0'%%&)*/*($552<>:071/8-%&620110$1;4989212:878985//%&%),%&.,%%)($$##%&#$%&*##&$%#'0$$)&)%(-*%%%'*'%&%'$#(*,$%'%&'%%()%&(%%)'+&--('&(+
@88a652b9-771e-45f6-aaae-f7d29bf024b5
TAAAGTACTGAACGGAATACTAACGAAAGTTGTACTACCTAAACAGTTCTGCTCGGGATCTAGTAGTCATACAATTGTCAAGTGGTCGCTTTGGTCGTCGACGTTCAAGACTCTCAACAGGTACTCTACCGCGTACGAACCATCTATCAACGGGTTCAACCAAATAGTAGGAGTAGAAAGCACTTACCATCGTACGAACTTTGACATATGAAGGTTCAAGGTAACCAAGGCGTAGTAGTGATGCCAGGTCTGTGTATAAAACTCCCTTTCTTATTTTGAGTCGTCAATGTAGTCGAGAAAGTATGTCACTTAGTGCCATTATTAGACAAGATAGTCCCGTTCTTAGTCGAAGTTCTTTGGCTGTAATAACAAAAGTAGAGCAGATACGATCCGAAAATTCATGGACACAGATATTTGAGATCAACATTTGATTCATATTCGATGTATTTATAATGATTCGGTTAGCGAGAGTTACATACAAAGTTAGTAATAGAAAGAAAGGGAAATAATAAATCAAAAGATTAAGCATGCAAACATTAAGAGGACACATATGTATTGGTGGCATTTGCGTTAAAAAACCCTACTCCATACTCATCCCGTCATTTATTTCATATCATCTCCCCCATCCATCCTACATAATCCTTTTCTCCC
+
&.-@<:<CA====86@7/$$*599388862+)$'+(+2>>8454)4*'&,+)'$$22?1,1*+24;5'%&#&$$$67)40968=8;//3'5://0//3,9:<;440.4<4'%#1/-)+&&&-()/#'%,0-)'*0<>0/+41)%$$/''#*&884*3.%/6;<02$2*686;7>,,*-(29(,+12:8<=7476:7976+-28410+3+15A84<,*)0306)')/0A<:629<38<5>:::0)%(.-($$$%%/)/2820$'/08:*+4<::*0.534680.)'-00:94,1/2//0210-+(*%++*510936533'#&%4:9<=5@:?@8=<%...*+%2=8;:875/:65$(0/,++)(-,*245'8;=A+0163&(549;-9:<<674440&2&%11-);;'288=B/;@=;8@?3&'(('''*+//)$#),2.)56''1.63./'((,131-7(%:110,4:5*(+7%%%%"&77@43453::43+5:9F74-,/%(/2&553337+32;?@G474==<:7'(473(%''*.'<;5;:?36428%,9<57<98;/++$))44(&61475/&%$&($%%$&&#&#$,++*'*($&$$(%-+.'*))&$(#$%$#))++)$$&$$$)+%"$$%.,&%#*+&($%4&+
@ea43c3ae-77a3-489e-bff7-b147eade722a
AATGATACGGCGACCACCGAGATTTACATTTTTCCCTACACGACGCTTCCTGATACAAATGAAAAAATCAATTTAACGTTTCTATTCATCACAATTTAGTAAGTCTTGTTGTAATAACAAAAGTAGAAAGATTACGATCCGAAATTTCATAGACCCAGATATTTGAGATTCAACATTTTGATTCGTTGACGTATTTATGTTGATTTAGTTAGCGAGTTACAAAAGTTAGTAAGAAGAAAGAGGAATAATAATCAAAGATTAAGCATATTAAGAGGACACATATGTATTGGTGGCATTTAATGTTAAAAAAAAATCCCATCCCTCCCATCACGCCATCCCCTTATTTATTTTTATACCTTATATCTTTCATCTATCCTCGCCCATTTATCACCTACAGTTTCAAACTCCTCC
+
;874+8))'%.1.23)+-*.27?(1/5--)'*+555')*(*(&92%/'&%$+,2*-12203/977''*&34A-A><<583+&055922305;9810315)*97:&+<59;8;6(89::;A>A5&+*&%/13.,$+)'*0,(46$835,-1'6..004378<<89794;;%#))*..1,1/./.)%183:8/69;5:5-'8=7;6*%%0)564,0;1'(./=>;<8=9994+4*9?/.1-,,037+893398,)/0:6<A2*)%%)'$$/-750+&*$&')*../54:(($3'&$(,+-0.+#*)*(/4752,&'.-)(&,+*&,)21+#$%"%('&&(0((*(,&$%'(),*)(#'&')),,/%&&%$#%$%#$&.$%#'((%)&&''$$(,'%(##%.-'.%$$(&'$(*`

**Comment by ydLiu-HIT** [comment]
Hi, 

I have pushed a new version of deSALT-v1.5.6(https://github.com/ydLiu-HIT/deSALT/archive/v1.5.6.zip) which can help you solve the error.

After you download the new version, you should first parse your annotation (SIRVome_isoforms_C_170612a.gtf) using Annotation_Load.py in the `src` folder and then run deSALT as before.

Good luck
Yadong

**Comment by HegedusB** [comment]
Hi Opplatek,
Have you found any solution for your problem? I think, I have the same problem too.  I get a segmentation fault when I try to use the annotation file (gtf). Can you give me a hint hove to resolve it.
Thanks,
Botond

**Comment by HegedusB** [comment]
Eventually, the deSALT worked fine. The problem was in my annotation. Sorry for the mistake. Cheers.
