### ISSUE TITLE
Error: index_build.c:4:10: fatal error: 'malloc.h' file not found 

### ISSUE THREAD

**Issue by OscarChou211** [ydLiu-HIT/deSALT#38]
Hi there, 

when I am trying to run make, it shows the following error, I wonder how to solve the problem? Thank you! 

cd deSALT/src/deBGA-master/
make
gcc -c  index_build.c -o index_build.o
index_build.c:4:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.

**Comment by ydLiu-HIT** [comment]
Hi,

"malloc.h" has been declared in <stdlib.h> in standard C library. So you can remove the included lines of <malloc.h> directly to solve the error.

Yadong

**Comment by OscarChou211** [comment]
Dear Yadong, 

Thank you very much for helping. I wonder where is the file stdlib.h? 

Thank you very much.

**Comment by ydLiu-HIT** [comment]
<stdlib.h>  is included in standard C library. You can include "stdlib.h" directly in your source file by
```
#include <stdlib.h>
```

Good luck
Yadong
