### ISSUE TITLE
Suitable for alignment to short reference?

### ISSUE THREAD

**Issue by gdonahue** [ydLiu-HIT/deSALT#6]
Hello,

I'm trying to use deSALT to align some Oxford Nanopore data to a really short "genome" (2-3 kb). I'm running into a problem in the indexing step. The command is:

`deSALT index Ref.fa Index`

I have tried running it through LSF with ample memory (64 GB RAM) or not. Doesn't seem to help. Here is the tail of the printed output:

> finish filling the hash blank
> begin creating unipath: 268435456
> number of supernode: 18
> number of linear node: 665
> number of forward Y branch node: 6
> number of reverse Y branch node: 6
> number of X branch node: 0
> number of linear blunt node: 1
> number of branch blunt node: 0
> number of end blunt node: 0
> number of ends blunt node: 0
> the max length of supernode: 384
> begin wrtting hash and kmer array and offset on unipath into file 678
> begin writing info about size of index files
> Program finished
> deleting div temporary index file folder
> rm -rf Index/div/ ---
> rm Index/unipath.seq ***
> finish index building
> 
> [desalt_index] Indexing undoing, deBGA index exit abnormally.

...and if I now attempt to run deSALT aln using the generated index, I get segmentation faults. Is there something which in principle should prevent the indexing from working due to the small size of the reference?

**Comment by ydLiu-HIT** [comment]
Hi,
Thanks for using deSALT first. DeSALT uses deBGA to generate index, but deBGA is not suitable for indexing really short sequence. In the source code of deBGA, deBGA set the starting pos of genome as 2048, so your 2-3kb genome may bey produce errors.

Best.
