### ISSUE TITLE
Questions about your simulated datasets

### ISSUE THREAD

**Issue by lauraht** [ydLiu-HIT/deSALT#8]
Hi Yadong,

We are trying to use and cite your simulated datasets shared at https://drive.google.com/drive/folders/16RpDYkdTCwOHmvoWNehnUp7nxrNt_Q7T?usp=sharing. We have a few questions about your datasets and would appreciate your help:

(**1**) About the human dataset in the folder `PBSimSamplingBasedReads/`: 
Does this dataset contain the simulated CCS reads or CLR reads?

(**2**) In this dataset, there are 3 fastq files generated using 3 different simulation depths: 
```
dataset_sim_human_g1.fastq
dataset_sim_human_g2.fastq
dataset_sim_human_g3.fastq
```
If we want to use the simulated reads of this dataset, we should `cat` these 3 files together, right?

(**3**) In this dataset, the transcriptome file `transcriptome_for_simulation.fa` contains **only and all** the expressed transcripts that were used to generate the simulated long reads, right?

(**4**) You used Ensembl annotation `Homo_sapiens.GRCh38.94.gtf` as the starting point of generating the transcriptome. In this process, you filtered out some transcripts. Do you also have the `.gtf` file that contains **only** the transcripts that were used for the simulation of this dataset? If you do not have that `.gtf` file, if we use the transcript names in the file `transcriptome_for_simulation.fa` to extract the records from `Homo_sapiens.GRCh38.94.gtf`, we should be able to get the `.gtf` file that contains **only** the transcripts that were used for the simulation of this dataset, right?

We would greatly appreciate your help.

Thank you very much!

**Comment by ydLiu-HIT** [comment]
Hi, lauraht

Thanks for using and cite your simulated datasets. I will reply to you point-by-point.
1) The human dataset in the folder `PBSimSamplingBasedReads/` doesn't contain simulated CCS and CLR datasets. The datasets in this folder are generated by a real ONT data(SRA Accession Number: SRR2848544) with PBSim sampling-based simulation. If you want to get CCS and CLR simulation datasets by PBSim model-based simulation with fixed parameter(PacBio CCS reads (error rate: 2%) and PacBio subreads (error rate: 15%)), you can download the datasets in the folder `PBSimModelBasedReads/`.
2) You can use the datasets separately or together. In the paper of deSALT, I benchmark the datasets separately for the evaluation of different expression levels(4x, 10x, 30x).
3) In this dataset, the transcriptome file transcriptome_for_simulation.fa contains only part of transcripts in annotations that were used to generate the simulated long reads. In folder `AllProteinCodingGene`, there have two transcriptome files which generated from all the protein-coding genes.
4) Of course, you can use the transcript names in the file transcriptome_for_simulation.fa to extract the records from Homo_sapiens.GRCh38.94.gtf. What's more, I have uploaded the GTF which used for stimulation to google drive. You can download the annotation file from: https://drive.google.com/file/d/1cVGZ1qM1YhHTliXVyHY1empIn2PGnIXn/view?usp=sharing. In each folder(human, mouse, drosophila), there are three GTF files(SS.gtf, AS.gtf, small.gtf) which are selected from Homo_sapiens.GRCh38.94.gtf for three specific types of gene sets,  i.e., genes with single splicing isoforms, genes with multiple splicing isoforms, and genes with short exons (<31 bp).

More detail please refer to deSALT paper. Thanks.

**Comment by ydLiu-HIT** [comment]
> Hi Yadong,
> 
> We are trying to use and cite your simulated datasets shared at https://drive.google.com/drive/folders/16RpDYkdTCwOHmvoWNehnUp7nxrNt_Q7T?usp=sharing. We have a few questions about your datasets and would appreciate your help:
> 
> (**1**) About the human dataset in the folder `PBSimSamplingBasedReads/`:
> Does this dataset contain the simulated CCS reads or CLR reads?
> 
> (**2**) In this dataset, there are 3 fastq files generated using 3 different simulation depths:
> 
> ```
> dataset_sim_human_g1.fastq
> dataset_sim_human_g2.fastq
> dataset_sim_human_g3.fastq
> ```
> 
> If we want to use the simulated reads of this dataset, we should `cat` these 3 files together, right?
> 
> (**3**) In this dataset, the transcriptome file `transcriptome_for_simulation.fa` contains **only and all** the expressed transcripts that were used to generate the simulated long reads, right?
> 
> (**4**) You used Ensembl annotation `Homo_sapiens.GRCh38.94.gtf` as the starting point of generating the transcriptome. In this process, you filtered out some transcripts. Do you also have the `.gtf` file that contains **only** the transcripts that were used for the simulation of this dataset? If you do not have that `.gtf` file, if we use the transcript names in the file `transcriptome_for_simulation.fa` to extract the records from `Homo_sapiens.GRCh38.94.gtf`, we should be able to get the `.gtf` file that contains **only** the transcripts that were used for the simulation of this dataset, right?
> 
> We would greatly appreciate your help.
> 
> Thank you very much!

**Comment by ydLiu-HIT** [comment]
> > Hi Yadong,
> > We are trying to use and cite your simulated datasets shared at https://drive.google.com/drive/folders/16RpDYkdTCwOHmvoWNehnUp7nxrNt_Q7T?usp=sharing. We have a few questions about your datasets and would appreciate your help:
> > (**1**) About the human dataset in the folder `PBSimSamplingBasedReads/`:
> > Does this dataset contain the simulated CCS reads or CLR reads?
> > (**2**) In this dataset, there are 3 fastq files generated using 3 different simulation depths:
> > ```
> > dataset_sim_human_g1.fastq
> > dataset_sim_human_g2.fastq
> > dataset_sim_human_g3.fastq
> > ```
> > 
> > 
> > If we want to use the simulated reads of this dataset, we should `cat` these 3 files together, right?
> > (**3**) In this dataset, the transcriptome file `transcriptome_for_simulation.fa` contains **only and all** the expressed transcripts that were used to generate the simulated long reads, right?
> > (**4**) You used Ensembl annotation `Homo_sapiens.GRCh38.94.gtf` as the starting point of generating the transcriptome. In this process, you filtered out some transcripts. Do you also have the `.gtf` file that contains **only** the transcripts that were used for the simulation of this dataset? If you do not have that `.gtf` file, if we use the transcript names in the file `transcriptome_for_simulation.fa` to extract the records from `Homo_sapiens.GRCh38.94.gtf`, we should be able to get the `.gtf` file that contains **only** the transcripts that were used for the simulation of this dataset, right?
> > We would greatly appreciate your help.
> > Thank you very much!

**Comment by lauraht** [comment]
Hi Yadong,

Thank you very much for your detailed response! It really helps!

We are now switching to the simulated CCS reads in the `PBSimModelBasedReads/human/` folder.

Regarding my question 3, I just wanted to get a clarification on one thing (sorry I did not make this question clear enough in the original post): 
Although the transcriptome file `transcriptome_for_simulation.fa` (which exists in the `PBSimModelBasedReads/human/` folder) contains only part of transcripts in the Ensembl annotations, this file contains **all** the expressed transcripts that were used to generate the simulated long reads in this dataset, right? Also, this file contains **only** the expressed transcripts that were used to generate the simulated long reads in this dataset, right?

About my question 4, thank you for uploading the `SS.gtf`, `AS.gtf`, and `small.gtf` files. Since I read that you filtered out the transcripts that are shorter than 200bp in the `merge_transcriptome.fa` file (that is the combination of the transcripts from `SS.gtf`, `AS.gtf`, and `small.gtf`) to get the `transcriptome_for_simulation.fa` file, the transcripts in `transcriptome_for_simulation.fa` are actually a subset of the transcripts in `SS.gtf + AS.gtf + small.gtf`, right? In this case, in order to get a `.gtf` file that contains **only** the transcripts that were used for the simulation of this dataset, I still need to use the transcripts names in `transcriptome_for_simulation.fa` to extract the records from `SS.gtf + AS.gtf + small.gtf` OR directly from `Homo_sapiens.GRCh38.94.gtf`, right?

Thank you so much for your help!

**Comment by ydLiu-HIT** [comment]
Hi，

1) As you say, the transcriptome file transcriptome_for_simulation.fa (which exists in the PBSimModelBasedReads/human/ folder), contains **only** the expressed transcripts that were used to generate the simulated long reads in this dataset.
2) In my operation,  I first generate transcripts sequence for each separate gtf file(`SS.gtf, AS.gtf and small.gtf`), then three transcriptome file generated such as `SS_transcriptome.fa, AS_transcriptome.fa and small_transcriptome.fa`, then I merge the three transcriptome file together and filter out the transcripts that are shorter than 200bp to get the original `transcriptome_for_simulation.fa`. So  `SS.gtf+AS.gtf+small.gtf` contains almost all the transcripts sequence for simulation except some sequence short than 200bp(maybe few sequences, not too much). If you want to get entirely gtf file corresponding to the sequences in `transcriptome_for_simulation.fa`, you can use the transcripts names in transcriptome_for_simulation.fa to extract the records from SS.gtf + AS.gtf + small.gtf.

Best!
